### PR TITLE
Replace debugger gem by byebug

### PR DESCRIPTION
**Pull request by yaf**
After some difficulty to install ruby debugger for ruby 2.0.0, I found
this issue on a project https://github.com/iracooke/protk/pull/11 and
then, change gem. I don't know if it's ok for you.

### CODE REVIEW

**Comment by yaf** [comment]
liked to #44

**Comment by yaf** [comment]
Still need this merge, event after last change about Gemfile

**Comment by krichtof** [comment]
A big sorry for the delay...

**Comment by yaf** [comment]
It's ok :-)

**Pull request merged**
